version: '3'
services:
  cuctf:
    build:
      context: .
    image: hotrod
    working_dir: /home/ctf
    devices:
      - /dev/kvm
    ports:
      - "9900:9900"
    entrypoint: /etc/run_xinetd.sh