FROM alpine:3.9

COPY ./app /app
WORKDIR /app

RUN apk add --no-cache                      \
        gcc g++ gnupg make libffi-dev       \
        openssl-dev python3   \
        python3-dev                         \
    && pip3 install -r requirements.txt

CMD ["./safenote.py"]

EXPOSE 7500
